services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.19
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

  spark-processor:
    image: apache/spark:3.5.0
    user: root
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: >
      /bin/bash -c "
      pip install confluent-kafka;
      /opt/spark/bin/spark-submit 
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.apache.hadoop:hadoop-aws:3.3.4 
      consumer.py"
    depends_on:
      - redpanda
      - minio